package inno.jago.ast;


import inno.jago.GoLexer;
import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
public enum TokenCode {

    DUMMY(-2),
    EOS(-1),
    ERROR(-3),
    GENERAL_COMMENT(GoLexer.GENERAL_COMMENT),
    LINE_COMMENT(GoLexer.LINE_COMMENT),
    END(GoLexer.END),
    WHITESPACE(GoLexer.WHITESPACE),
    BREAK(GoLexer.BREAK),
    DEFAULT(GoLexer.DEFAULT),
    FUNC(GoLexer.FUNC),
    INTERFACE(GoLexer.INTERFACE),
    SELECT(GoLexer.SELECT),
    CASE(GoLexer.CASE),
    DEFER(GoLexer.DEFER),
    GO(GoLexer.GO),
    MAP(GoLexer.MAP),
    STRUCT(GoLexer.STRUCT),
    CHAN(GoLexer.CHAN),
    ELSE(GoLexer.ELSE),
    GOTO(GoLexer.GOTO),
    PACKAGE(GoLexer.PACKAGE),
    SWITCH(GoLexer.SWITCH),
    CONST(GoLexer.CONST),
    FALLTHROUGH(GoLexer.FALLTHROUGH),
    IF(GoLexer.IF),
    RANGE(GoLexer.RANGE),
    TYPE(GoLexer.TYPE),
    CONTINUE(GoLexer.CONTINUE),
    FOR(GoLexer.FOR),
    IMPORT(GoLexer.IMPORT),
    RETURN(GoLexer.RETURN),
    VAR(GoLexer.VAR),
    L_PAREN(GoLexer.L_PAREN),
    R_PAREN(GoLexer.R_PAREN),
    L_CURLY(),
    R_CURLY(),
    L_BRACKET(),
    R_BRACKET(),
    ASSIGN(),
    COMMA(),
    SEMI(),
    COLON(),
    DOT(),
    PLUS_PLUS(),
    MINUS_MINUS(),
    DECLARE_ASSIGN(),
    ELLIPSIS(),
    LOGICAL_OR(),
    LOGICAL_AND(),
    EQUALS(),
    NOT_EQUALS(),
    LESS(),
    LESS_OR_EQUALS(),
    GREATER(),
    GREATER_OR_EQUALS(),
    PLUS(),
    MINUS(),
    CARET(),
    ASTERISK(),
    AMPERSAND(),
    OR(),
    DIV(),
    MOD(),
    LSHIFT(),
    RSHIFT(),
    BIT_CLEAR(),
    EXCLAMATION(),
    RECEIVE(),
    IDENTIFIER(),
    INT_LIT(),
    FLOAT_LIT(),
    IMAGINARY_LIT(),
    RUNE_LIT(),
    STRING_LIT()

    @Getter
    private final int value;
}
